field.widget.settings.gated_file:
  type: mapping
  label: 'Gated File widget settings'
  mapping:
    form:
      type: string
      label: 'Form Machine Name'
    form_per_file:
      type: boolean
      label: 'Allow Form per file'
